version: '3'
services:
  kv1:
    build: ./docker/.
    expose:
      - "22"
      - "4001"
    networks:
      performance_test_ntwrk:
        ipv4_address: 172.172.1.2
    volumes:
      - "./:/opt/app"


networks:
  performance_test_ntwrk:
    ipam:
      driver: default
      config:
        - subnet: 172.172.1.0/24
